version: "3.4"

services:
  ucr:
    image: docker.iscinternal.com/grongier/ucr:2020.1
    container_name: ucr
    hostname: ucr
    build:
      context: ucr
    volumes:
       - .:/tmp
    ports:
      # Superserver
      - "51773:51773"
      # Webserver/management portal http://localhost:52773/csp/sys/%25CSP.Portal.Home.zen
      - "52773:52773"
      # HL7 inbound adapter
      - "62115:62115"
  iris:
    image: store/intersystems/irishealth-community:2020.2.0.196.0
    hostname: iris
    ports:
      - "51776:51773" # 51773 is the superserver default port
      - "52776:52773" # 52773 is the webserver/management portal port
    volumes:
       - .:/tmp
