version: "3.4"

services:
  ucr:
    image: docker.iscinternal.com/grongier/ucr:2020.1
    container_name: ucr
    hostname: ucr
    build:
      context: ucr
    volumes:
       - .:/tmp
    ports:
      # Superserver
      - "51773:51773"
      # Webserver/management portal http://localhost:52773/csp/sys/%25CSP.Portal.Home.zen
      - "52773:52773"
      # HL7 inbound adapter
      - "62115:62115"
  iris:
    image: iris-fhir-to-sda:latest
    container_name: iris
    hostname: iris
    build:
      context: fhir-r4-to-sda3
    ports:
      - "51776:51773" # 51773 is the superserver default port
      - "52776:52773" # 52773 is the webserver/management portal port
    volumes:
       - .:/tmp
  clinicalviewer:
    image: docker.iscinternal.com/grongier/clinicalviewer:2020.1
    container_name: clinicalviewer
    hostname: clinicalviewer
    build:
      context: clinicalviewer
    volumes:
        - .:/tmp
    ports:
      # Superserver
      - "41773:41773"
      # Webserver/management portal http://localhost:52773/csp/sys/%25CSP.Portal.Home.zen
      - "42773:42773"
